language: node_js
node_js:
  - 14

install:
  - echo '*****Build Starts*****'
  - echo 'Installing Dependencies'
  - npm install
  - echo 'Running Tests'

Script:
  - cd trailtracker
  - npm run test -- -- no-watch 
 
 
  
 
