language: node_js
node_js:
  - 14

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - cd trailtracker
  - echo '*****Build Starts*****'
  - echo 'Installing Dependencies'
  - npm install
  - echo 'Running Tests'

Script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
 
 
  
 
